### ISSUE TITLE
Self-Terminating / Expiring Persistence Payloads

### ISSUE THREAD

**Issue by True-Demon** [zerosum0x0/koadic#104]
# Feature Request: Self-terminating persistence modules

Something that would be extremely useful for red team and pentesting engagements is the ability to set on persistence modules is a self-termination condition so that the RAT does not continue to persist beyond certain dates/conditions. I recognize the listeners are able to expire payloads after a certain time, but based on what I've seen, the persistence modules don't do any sort of cleanup on themselves once they've established persistence. 

The problem with this is that if you lose contact with a zombie, you can't clean up after yourself properly, and you end up with a client that gets a mshta window pop-up every time they log onto their machine. It's certainly not OPSEC safe, and it's most definitely annoying for a client that doesn't know how to clean it up themselves.

I wouldn't mind taking a crack at this myself in my spare time, but if it wouldn't be terribly difficult for you guys (being way more familiar with the source code than I am), you'd probably be able to implement it way faster than I would.

**Comment by TheNaterz** [comment]
OK sure, this whole idea makes sense and I know exactly what you mean. I've been sitting here thinking of some ideas. I'll get back to you on this tomorrow after I've played around with some stuff.

**Comment by TheNaterz** [comment]
May have made a bit of a breakthrough. If I use mshta to run an HTA file locally that attempts to spawn a new Zombie, it will not pop a big white box if it fails.

Here's a PoC: https://gist.github.com/TheNaterz/084aa02999af3794e369150d61ca137b

This will create a process that runs a defined mshta stager, waits 10 seconds, then kills the created process. If you point the URL at a non-existent Koadic, you'll see that no box appears and the mshta process gets cleaned up.

This is both good and bad news. Good news because we have a lot more flexibility to do things instead of having to rely on some janky one-liner. The bad news is that, unfortunately, we'll need to drop an HTA on the target system. We haven't played around with Alternate Data Streams yet, so this seems like the perfect time to put it into practice. We'll have to create a file in some area that won't get wiped on reboot and won't be seen as suspicious by a typical user.

A question I have is, would you expect this dropped HTA to cleanup the persistence regardless of whether or not a Zombie comes back? Would be a clean solution, but someone might be annoyed that they need to run the persistence module again. Thoughts?

**Comment by TheNaterz** [comment]
Alright, after internal discussion with the team here, we've decided that the best course of action isn't to self-terminate a persistence module on first failure as default behavior. The reason being because you can't always determine why a Zombie isn't able to call back and for how long. If a connection to the target is spotty, you wouldn't want your Zombie to just peace out, you'd want it to keep trying. So here's my current plan of attack:

- Drop an HTA, set the persistence command to call mshta on this file
- When the HTA is called, it'll attempt to spawn a Zombie (white box will never appear)
- Wait a few seconds, then cleanup the first mshta process (if Zombie was successful, it'll fork to rundll32)
- User defined boolean flag: if true, cleanup persistence (we could also implement a failure count condition as well), else, wait like 60 seconds and try spawning a zombie again

As a last resort, Koadic can print a script to the console, and the location of the HTA, that can be used to cleanup the persistence offline (or if you get access to the box some other way) in the event that a Zombie is unable to come back. The PoC above is like 70% of the way there. Should have a solution out later today.

**Comment by True-Demon** [comment]
It may also be worthwhile to give users the option to set a couple of new option fields like "retry_attempts" and "retry_delay" so users can specify a set number of retries and wait times between attempts to connect before the zombie decides the listener is dead and self terminates. I think the main idea should be to give the user as much flexibility as possible, since we're all supposed to be responsible adults. This would let the user be able to define what they consider to be ideal behavior in any given scenario.

**Comment by TheNaterz** [comment]
Agreed. Was actually working on that when you mentioned it!

Here's the file I'm thinking of dropping for the registry method: https://gist.githubusercontent.com/TheNaterz/2c1af08e556b53d7f46db36ea30a8caf/raw/51357420fa3b2f033a2bb7913be300b457b7ecef/registry.hta

The other methods just need to swap out the persist.clean function and it'll be good to go. We'll pass the template through our obfuscation methods and populate the vars. Then we can upload and it should be OK. We're thinking about landing this in %APPDATA% as a default, but this will be user defined as well.

**Comment by True-Demon** [comment]
Neato. Thanks for the quick turn around. I will see about making a few new modules of my own for this to return the favor. :v:

**Comment by TheNaterz** [comment]
Cool cool. I'll see about finishing everything off this weekend, but sometime next week for sure.

**Comment by TheNaterz** [comment]
I've got a solution working for registry persistence, but only when we place payload under HKCU. HKLM doesn't launch under an elevated process, so we don't have permissions to remove the key for self-termination. This used to be an automated decision, but we'll default to HKCU and make this an advanced option. I'll check the other methods to make sure elevated persistence gives elevated permissions.

**Comment by TheNaterz** [comment]
Made final touches to registry persistence and pushed here: bed7bf8c6633d8fbe2bf93f5199635a12c415522

Just need to port over the other ones.

**Comment by TheNaterz** [comment]
Elevated schtasks runs as NT AUTHORITY/SYSTEM which makes sense, but unfortunately means we can't place the payload in %APPDATA%. %ALLUSERSPROFILE% is writeable by all, same for all users, and is also a hidden folder so we'll make that the default for this method.

Based on my testing, and confirmed with some Googling, Windows 10 does not honor OnIdle scheduled tasks. Best bet is to only run this module elevated where possible.

deffaf3d81af1483badc0a4e082a1266900691b5

**Comment by TheNaterz** [comment]
Should be good to go: 5f4fc824e09d7b60bd1bad22409f08df6d44ebfc

Thanks for the suggestion! Test these out whenever, reopen or submit a PR if anything comes up.
