### ISSUE TITLE
reflectdll_excel.js not working

### ISSUE THREAD

**Issue by alligator-man** [zerosum0x0/koadic#112]
I loaded the implant/inject/reflectdll_excel.js and, even after specifying a DLL, I did not notice any injection happening on the zombie end. I also read through the code itself and it didn't look like there was any spot where the actual injection was occurring.

Is this feature partially implemented or am I missing a step? If this is partially implemented, is it possible I could get a hint on how to try and fix the issue? 

Thanks

**Comment by TheNaterz** [comment]
We've still got a few modules floating around which don't work or aren't implemented at all. This is mostly due to whether or not we have a need for this on our own team. If we need to inject a DLL, dotnet2js has been working just fine for us. I don't even have Excel to develop and test this on.

The current implementation that we have doesn't reference a DLL at all in the javascript, looks like a PoC to pop cmd.exe. I would imagine if you took a look at https://blog.didierstevens.com/2008/06/05/bpmtk-how-about-srp-whitelists/ and adapted it to our module, you might get somewhere.
