### ISSUE TITLE
Possible to enable SSL in communication between zombie and Koadic ?

### ISSUE THREAD

**Issue by Anton19780301** [zerosum0x0/koadic#113]
Good day.
Is it possible to enable SSL in communication between zombie and Koadic?
Otherwise, the antivirus responds to the transition infection. Maybe this will help

**Comment by Anton19780301** [comment]
As I understand it,  can enable TLS if i'm place Koadic on the Internet, on a site, and that he has access to the site with certificates. But I only have a local area network and for security reasons use of the Internet is prohibited. Is there no way to test using Koadic without the Internet and enable TLS ?
PS 
Is there a detailed tutorial on Kodiac?

**Comment by TheNaterz** [comment]
So right, TLS communications as they currently stand in Koadic has some limitations. I think in order to get that working on a local net, you would have to edit the hosts file on your target, but I haven't tested that so I don't even know if that translation would be respected.

Your other option would be using obfuscated payloads. We have an option on stagers to xor cipher the Javascript (set OBFUSCATE xor) with a random key that decrypts and evals on the other side. Now, passing a huge blob of data to an eval is a red flag for some AV, so this has limitations as well. I'm planning on doing more testing with using "eval without eval" techniques to run Javascript, so we'll see how much mileage we can get out of that.

Check the wiki for some things you can do with Koadic and check 'help ____' for detailed usage while in Koadic. I'm adding and improving stuff all the time, so keep a look out on commits.
