### ISSUE TITLE
Windows Defender detects Koadic

### ISSUE THREAD

**Issue by sizzthehedgehog** [zerosum0x0/koadic#123]
Hi there,
Probably a very basic challenge for you guys, but is there a way to run / launch the mshta command from the latest Windows 10 Pro build without havin Koadic detected by Windows Defender? 

Version 10.0.17763 Build 17763 - Windows 10 Pro

Or is there no way to achieve this and Koadic can be used only with older releases of Windows 10? 
Any feedback appreciated.

**Comment by zerosum0x0** [comment]
Every couple months comes a new detection, and we RE/fiddle stuff until it works again. The old cat and mouse game. We weren't immediately aware that there were new detections in place, but now that we know we'll definitely take a look into it.

**Comment by zerosum0x0** [comment]
I'm actually going to close the issue because we don't try to make a big deal out of when we do these type of changes, because any fanfaire just leads to them getting nerfed quicker. If you're trying to get something done in the next week or so it's probably a no-go, but know that we are still actively developing bypasses for AVs where we can.

**Comment by slavadba** [comment]
Hi,

so - 5 months have passed, is there any solution?
At the moment, the score in the game is strongly in favor of WD
