### ISSUE TITLE
implant/scan/tcp

### ISSUE THREAD

**Issue by k0l0ss** [zerosum0x0/koadic#124]
Hello,
I am trying to scan a remote host in lan.
scan job never finish.
![jobs_run](https://user-images.githubusercontent.com/29979342/72201553-a5fe6a80-3455-11ea-9464-4531b6aee698.png)
the job detail won't show
![jobs_help](https://user-images.githubusercontent.com/29979342/72201555-a8f95b00-3455-11ea-9186-2f5836f0ee08.png)
can't kill it either
![kill_job](https://user-images.githubusercontent.com/29979342/72201556-ab5bb500-3455-11ea-8f71-5dfc7599c916.png)
ports on remote
![nmap](https://user-images.githubusercontent.com/29979342/72201557-adbe0f00-3455-11ea-81fd-d4cd75c86baa.png)

Ideas?

Thank's

**Comment by TheNaterz** [comment]
We switched up how options get set for a job a while back and I missed this module. The zombie is throwing errors about missing semicolons, probably will want to clean those up. Lemme see if I can make a quick fix.

**Comment by TheNaterz** [comment]
Pushed a fix, the RHOSTS and RPORTS should now be js arrays again. Updated the timeout by another second, going back to the old method of testing port 0 for CHECKLIVE.

**Comment by k0l0ss** [comment]
![port_scan1](https://user-images.githubusercontent.com/29979342/72203040-eca89080-3466-11ea-9827-36369febd00b.png)
Not working yet.

**Comment by TheNaterz** [comment]
Increase the timeout or set CHECKLIVE false.

**Comment by k0l0ss** [comment]
CHECKLIVE false did the job, seems working allright now.
Can we know what CHECKLIVE is based of? 
Thank you

**Comment by TheNaterz** [comment]
Here's the logic under data/implant/scan/tcp.js:
https://github.com/zerosum0x0/koadic/blob/b96a34a04c9810180416a528616d32eac65bcba6/data/implant/scan/tcp.js#L61-L80

We're checking for whether or not port 1 is open or closed (was port 0, but unreliable so still sticking with port 1). If the host is up, we should see a "closed" status for port 1. Any other status should mean the host isn't up (I've never seen port 1 open legitimately, so should minimize false positives). Timeout is also important here, because if we don't wait long enough for a response of some kind, we just say that the status is "open". Might be an oversight, but I'm not too worried about it enough.

**Comment by k0l0ss** [comment]
Thank you :+1:
