### ISSUE TITLE
Elevated var not showing correctly

### ISSUE THREAD

**Issue by k0l0ss** [zerosum0x0/koadic#126]
Believe me it is not a system or privileged account, but:
![elevated_yes](https://user-images.githubusercontent.com/29979342/72208821-bb9c8000-34a7-11ea-8b22-654d812f3c62.png)
Even so, tried an implant which needed and:
![Adj_priv](https://user-images.githubusercontent.com/29979342/72208823-c0613400-34a7-11ea-8219-663187bb49bd.png)
elevating via implant+post execution worked all right.
Something is broken with the elevated var showing incorrectly for win2012r2 build 9600.
Pd. just realized it says status: dead. it was not.

**Comment by TheNaterz** [comment]
We're checking whether a Zombie is elevated or not by running:
`net pause lanmanserver`

If you get a System Error 5, then you are not elevated. Anything else, and I believe that you should be. If you have permissions to run the action, running pause doesn't do anything, which is why we chose it. It's possible that there are multiple privilege levels that allow a user, who is not an administrator, to perform this action.

What output do you get if you run `net pause lanmanserver`? Could you also post `whoami /groups`?

**Comment by TheNaterz** [comment]
I might as well change up the elevation detection to run whoami /all and check for the presence of SeDebugPrivilege. We had a small discussion about it in the office, it'll definitely be more reliable. I don't know if it will be called the same thing across different languages of Windows, but we can cross that bridge when we come to it.

**Comment by TheNaterz** [comment]
There are two different Zombies in those screenshots. I only see that Zombie 0 was elevated, was Zombie 1 also elevated? Was Zombie 0 manually killed? We don't dispatch jobs to manually killed Zombies since there are no cases where that Zombie will be able to run that job. If you didn't manually kill the Zombie, you should have seen a status message that told you that the Zombie timed out.

**Comment by k0l0ss** [comment]
Sorry, I was busy with other stuff and couldn't get to this until now.
> What output do you get if you run `net pause lanmanserver`? Could you also post `whoami /all`?
Did you made any changes? the output of zombies <id> now shows correctly the elevated value.
lanmanserver now returns System error 5 has ocurred. Access is denied.
 whoami /all is hard, too many entries of the domain I am working with and don't wanna mess with it.
> There are two different Zombies in those screenshots. I only see that Zombie 0 was elevated, was Zombie 1 also elevated?
It took me a while to remember what I did, I will try to explain:
I dropped the mshta command on a cmd, then zombie 0 hooked. It was an unprivileged cmd with an unprivileged user.
The output of zombies 0 was elevated=YES
It could not be disconnected as it was freshly hooked.
Later on (after I closed that instance) I wanted to post this and recreated and environment. This time I had done a few more tests before I took a screenshot of mimikatz failing, so it was with zombie 1 instead of 0. But represents same situation. Sorry about the inconsistency.

This time around, doing same chain process, took me to show correct values for status and elevated.
If you did not change anything regarding these two, then I did something wrong or did not reproduced correctly.

**Comment by TheNaterz** [comment]
Sorry, been busy. Yes, I pushed an update to detecting elevation. Now we search for SeDebugPrivilege in whoami /all to determine elevation. The previous way looked for the 5 in System Error 5 as you were saying. It was an attempt to make things language agnostic, but the new way should work too, I believe. Glad to see that it's working!
