### ISSUE TITLE
Communication through system's default http proxy

### ISSUE THREAD

**Issue by Arno0x** [zerosum0x0/koadic#14]
Hi,

I've been trying to make koadic work through a web proxy (the system's default one). While the stagers I tried (mshta and regsvr) do automatically perform their initial call through the web proxy allowing the retrieval of the initial JScript file, the next communication calls from the script doesn't seem to use the system's default proxy and instead try a straight connection back to the remote server (obviously failing).

Seems like the Koadic.http object (either WinHttp.WinHttpRequest.5.1 or Microsoft.XMLHTTP) do not take into account the system's proxy. Doesn't seem right...

Any idea ?
Thanks.

**Comment by Arno0x** [comment]
Well actually, it's just the WinHttp.WinHttpRequest.5.1 object that fails using the system's default proxy. The  Microsoft.XMLHTTP works just fine without any extra line of code.

Why use the WinHttp.WinHttpRequest.5.1 by default over the Microsoft.XMLHTTP which is a fallback ?

**Comment by zerosum0x0** [comment]
The initial communications aren't from any COM objects we own, they're performed through the underlying .exe because we supply a URL in the command line.

Here is where we create COM HTTP objects:

https://github.com/zerosum0x0/koadic/blob/master/data/stager/js/stdlib.js#L252

While I don't remember why this order was chosen (the code for that was written nearly a year ago), I do know that after extensive testing of Win2k through Win10 it was the best solution. I did not test through proxies.

Does flipping the order of the calls in this file fix the proxy issue? If it does fix that issue, and we can get reliable behavior on Windows 2000, we can change the order.

**Comment by Arno0x** [comment]
_>> The initial communications aren't from any COM objects we own, they're performed through the underlying .exe because we supply a URL in the command line._

Yes, definitely, and that's what I like with those mshta/regsvr binaries is that they're automatically proxy aware and proxy friendly, even performing transparent user authentication against the proxy server.

_>> Does flipping the order of the calls in this file fix the proxy issue?_

Yes, it works like a charm using Microsoft.XMLHTTP by default (removing completely the use of WinHttpRequest COM object). Tested successfully on Win7 and Win10.

Now I have no means of testing on other Windows flavors (Win2000, Vista ?, XP ?)

**Comment by Arno0x** [comment]
oh, and I forgot to mention that having "proxy friendly" C2 communication is a "must have" in almost any corporate environment :-)

**Comment by zerosum0x0** [comment]
Completely agree. Will get this tested on Windows 2000 on up sometime tomorrow and fix if no bugs.
