### ISSUE TITLE
Thunderstruck not working 

### ISSUE THREAD

**Issue by ishan-saha** [zerosum0x0/koadic#144]
![image](https://user-images.githubusercontent.com/37301924/102698758-c8a02280-4265-11eb-933f-45e1d2d07f90.png)

The thunderstruck command is not working in the implant section

**Comment by TheNaterz** [comment]
Yeah we were relying on some janky regex to figure out the millisecond length of the video. So long as YouTube doesn't decide to change up "approxDurationMs", I have a pretty solid alternative janky regex fix I can implement.

There's also an interesting consideration in the fact that advertisement videos exist and since YouTube is all about the dolla dolla bills yall, these ads are gonna play at the beginning of the video for pretty much anything that would be worth launching on a target for fun. So just be aware that Thunderstruck attempts may be preceded by an announcement that you could save money on your car insurance.
