### ISSUE TITLE
Possible to use Veil Evasion to avoid AV

### ISSUE THREAD

**Issue by PowerPress** [zerosum0x0/koadic#25]
Is it possible to use Veil Evasion or anything else to avoid AV from detecting this C2?

**Comment by TheNaterz** [comment]
The only thing that would allow koadic to completely bypass AV would be to obfuscate the JScript and VBScript. There are a couple of solution out there already, it just needs to get implemented. For the time being, koadic already bypasses most AV simply because they haven't implemented signatures.

We haven't had an issue with being detected on engagements yet, but that will change as koadic grows in popularity. Rest assured that AV evasion is on our radar.
