### ISSUE TITLE
Command Syntax

### ISSUE THREAD

**Issue by vvalien** [zerosum0x0/koadic#5]
I started designing a whole "command shell" with a easy to use syntax for Empire using rest, you might be interested. My approach was simple....

handlers = (established listeners)
listeners = (any module that listens for connect)
modules = (post exploit modules)
sessions = (agents, zombies)
stagers = (stagers)

The basic commands are fairly self explanatory, all can be used with the above commands.
use, show, info, kill, exploit

I set the "context" just as koadic does so after using a listener you could do show options, but also you could do show sessions, or show handlers from anyplace to get a list.
 
I just thought someone might be interested as we now have 3 different open-source command variants to remember.

**Comment by zerosum0x0** [comment]
Everything sort of exists in a super state that's within the Shell object right now. Sloppy design, and some stuff deeper in the internals rely on it.  Eventually I want to move the irrelevant parts to a "Koadic" object, so that we can have a headless version and an API.

We have the command aliasing that you added so feel free to add more.
