### ISSUE TITLE
 I can not create Stager.. mshta, regsvr and another after update koadic 

### ISSUE THREAD

**Issue by OldBo** [zerosum0x0/koadic#53]
Kali Linux 2018

Traceback (most recent call last):
  File "/root/koadic/core/shell.py", line 50, in run
    self.run_command(cmd)
  File "/root/koadic/core/shell.py", line 83, in run_command
    self.actions[action].execute(self, cmd)
AttributeError: 'module' object has no attribute 'execute'

![gp](https://user-images.githubusercontent.com/37963053/39237069-29a059e0-4883-11e8-8ed9-5d3a8a3907ae.png)

**Comment by TheNaterz** [comment]
I can't replicate this behavior on my box, but I'll run a Kali instance to check just to be sure. Can you confirm that the execute method is present in core/commands/run.py?

**Comment by OldBo** [comment]
If I can run koadic with python3.6 that OK)

**Comment by CalfCrusher** [comment]
Soluiton to this problem is simply and doesn't involve in Python version, Koadic can run just with Python3 or Python3.9. In my case the problem was caused by WRONG stager. So before generate stager for wmic you need to CHANGE stager:

$ use stager/js/wmic 

then createstager

I'm feeling dumb becase i had this error for a while.
