### ISSUE TITLE
Server 2003 Timeout

### ISSUE THREAD

**Issue by BLTSEC** [zerosum0x0/koadic#63]
Works on my Windows 10 target but not my server 2003 target.

[*] Verbose mode: On
[v] handler::handle() - Incoming HTTP from ('x.x.x.x', 1155)
[v] handler::handle_new_session()
[+] Zombie 1: Staging new connection (x.x.x.x)
[v] handler::reply() - sending status 200 with 12373 bytes to ('x.x.x.x', 1155)
[v] handler::handle() - Incoming HTTP from ('x.x.x.x', 1156)
[v] handler::find_session() - found session.key = 499ea8fb505d41c1b1c4489d4296f7c3
**[v] session::parse_user_info() - 'split(...).1' is null or not an object**
[v] handler::reply() - sending status 200 with 0 bytes to ('x.x.x.x', 1156)
[!] Zombie 1: Timed out.

**Comment by TheNaterz** [comment]
I kept searching for a python error, but since this is a verbose statement that prints 'data', that's a javascript error. Luckily there's only 1 split during Koadic.user.info() and it's here: https://github.com/zerosum0x0/koadic/blob/master/data/stager/js/stdlib.js#L262

Does ipconfig on that 2003 not have IPv4 in there? I'm adding error handling and a fallback, but that would be interesting to know.

**Comment by TheNaterz** [comment]
Oh OK I just realized that the string for 2003 is just 'IP Address'. All add some shtuff in there and have push it out in a few.

**Comment by TheNaterz** [comment]
Go ahead and try that one. It should be correct and in the case of any errors, it will set the IP to the IP of the request. If we can't get to a super reliable method of getting the correct IP each time, I might add the ability to manually edit a Zombie's IP.

**Comment by BLTSEC** [comment]
Seems to be working now. Thanks!
