### ISSUE TITLE
Future Koadic Enhancment - GUI

### ISSUE THREAD

**Issue by TheBrokenWasp** [zerosum0x0/koadic#78]
Ok here goes... Ya think you can add an Armitage/Cobalt Strike-like UI?

**Comment by TheNaterz** [comment]
We currently don't have any plans for a GUI. The advantages of Armitage and Cobalt Strike include visualization of a network during post-exploitation, and they can do it effectively because of their ability to effectively pivot through compromised hosts. Koadic has some pretty limited pivoting capabilities and Zombies can't elevate privileges within the same process. If I picture network visualization in a GUI for Koadic, I would expect a flat-looking network with a number of duplicate Zombies of varying privileges. It would be cool to have something that looks like Armitage or Cobalt Strike, but I feel like the actual execution wouldn't have many advantages over the console approach.

**Comment by TheBrokenWasp** [comment]
Maybe once Koadic has been improved enough to have an advantage with a GUI?

**Comment by TheNaterz** [comment]
Maybe.

**Comment by TheNaterz** [comment]
Lol nah
