### ISSUE TITLE
Periodic Restore Creation - Enhancement Request

### ISSUE THREAD

**Issue by Clutchisback1** [zerosum0x0/koadic#85]
It be nice to be able to save a Koadic session in the event that someone accidentally ctrl + Cs out

**Comment by TheNaterz** [comment]
Yeah we could make like a restore file. It wouldn't be able to save zombie connections, those would die when the web server stops, but everything else we could load back in I'm pretty sure. I'll try working on something this week.

**Comment by Clutchisback1** [comment]
YASSSSSsssssssssss!!! Thanks!! friggin awesome! :+1:

**Comment by TheNaterz** [comment]
I didn't test too extensively, so reopen if you get an exception.

**Comment by Clutchisback1** [comment]
Hey, I finally got around to testing this and it seems like the saved creds and data arent automatically saving to the restore.json file. So when I cat out the restore.json file it's empty.

**Comment by Clutchisback1** [comment]
correction...not empty but has empty placeholders....

**Comment by TheNaterz** [comment]
My guess is that you're overwriting the restore.json file without knowing it. The following situation would make this happen:

1. Run Koadic like normally, run jobs, gets creds, etc.
2. Exit Koadic.
3. Run Koadic again without specifying the restore file.
4. Realize that Koadic was not run with the restore file then exit Koadic.
5. The restore file is now empty.

Here's where all the magic happens:
https://github.com/zerosum0x0/koadic/blob/master/core/commands/exit.py#L31-L62

As you can see, on exit, we overwrite the restore.json file with whatever is populated in the current Koadic instance. Obviously, the current solution isn't ideal because if you forget to run Koadic with the restore file and then forget to move or rename the restore file before exiting, you'll lose all the information in the restore.

Better solution probably entails creating a folder and populating this with restore files that include timestamps in the name. You'll create a new restore on exit every time, but at least all information is retained. I'll reference a pull here when it's done.

**Comment by Clutchisback1** [comment]
Thanks for getting back with me. 

So I have my buddy testing this out on his internal assessment as we (I) speak. In his situation someone rebooted his drone and a restore.json file was never created. I also checked to see if he was on the current version of Koadic and he is in which I also confirmed that he had the --restore option. Luckily he created a creds.txt file where he backed up his creds so there wasn't much loss there. But this has been what we've observed so far. Hope that helps.

**Comment by Clutchisback1** [comment]
I also appreciate the initiative in making that process better. I agree that making the unique restore files would make me love this app all the more! :heart:

**Comment by TheNaterz** [comment]
I hadn't even thought of power loss scenarios. Currently, creating a restore file is only ever triggered when exit gets called. So if the process is killed at all before that happens, the file is never created. The solution there is writing a restore to disk every so often given that a change has occurred, maybe once a minute? I'll get to working on that as well when I get the time.

**Comment by Clutchisback1** [comment]
That's awesome! Thanks for building this out. I guess begging can pay its dividends!? I can have some folks test this out once everything gets ironed out. That sounds like a great solution.

**Comment by TheNaterz** [comment]
Go ahead and pull now. Koadic will make a 'restores/' dir and place periodic restores in there. Every 60 seconds, if there's been a change, Koadic will write to this new file. I'm keeping the old behavior as well, so whenever you exit, Koadic will write the current state to 'restore.json'. I think it's nice to have that most recent state in there in case you don't wanna go digging through old restores.

https://github.com/zerosum0x0/koadic/commit/fc8ebf9a1935515aecdf3af1b3992faf3d844ae8

Had another idea while writing this update actually. If you have no state, it won't overwrite 'restore.json'!

e28db12

Again, didn't test super extensively, so reopen if you have any issues.

**Comment by Clutchisback1** [comment]
Super, thanks for being so active. I'll try to test this out over the weekend! If i can't get to it I'll have some of my co-workers (Coalfire) give it a go. Thanks man 1000% :muscle:
